In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x =  [1,2,3,4,5]
h =  [2,0,1,3]
N = len(x)+len(h)-1
y = np.convolve(x,h,'full')
print(y)

[ 2  4  7 13 19 13 17 15]


In [4]:
# DFT
def DFT(x,N):
    X = np.zeros(N,dtype = 'complex_')
    for k in range(N):
        for n in range(N):
            X[k] = X[k] + x[n]*np.exp(-1j*2*np.pi*k*n/N)
    return X

In [3]:
# DFT
def DFT(x,N):
    X = np.zeros(N, dtype='complex_')
    for k in range(N):
        for n in range(N):
            X[k] = X[k]+ x[n]*np.exp(-1j*2*np.pi*k*n/N)
    return X

In [5]:
# IDFT
def IDFT(X, N):
    y = np.zeros(N,dtype = 'complex_')
    for n in range(N):
        for k in range(N):
            y[n] = y[n] + X[k]*np.exp(1j*2*np.pi*k*n/N)
    
    return y/N

In [4]:
# IDFT
def IDFT(X,N):
    y = np.zeros(N, dtype='complex_')
    for n in range(N):
        for k in range(N):
            y[n] = y[n]+X[k]*np.exp(1j*2*np.pi*k*n/N)
    return y/N

In [7]:
x = np.pad(x, (0, N-len(x)), 'constant')
h = np.pad(h, (0, N-len(h)), 'constant')
X = DFT(x,N)
H = DFT(h,N)
Y = X*H
y = np.real(IDFT(Y,N))

[ 2.  4.  7. 13. 19. 13. 17. 15.]
[ 9.00000000e+01+0.00000000e+00j -2.19497475e+01+1.77781746e+01j
 -3.00000000e+00+1.10000000e+01j -1.20502525e+01-2.22182541e+00j
  1.25979822e-30-2.57175828e-15j -1.20502525e+01+2.22182541e+00j
 -3.00000000e+00-1.10000000e+01j -2.19497475e+01-1.77781746e+01j]


In [8]:
x = np.pad(x,(0,N-len(x)),'constant')
h = np.pad(h, (0,N-len(h)),'constant')
X = DFT(x,N)
H = DFT(h,N)
Y = X*H
y = np.real(IDFT(Y,N))
print(y)

[ 2.  4.  7. 13. 19. 13. 17. 15.]
