In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
N = 15
L = 5
M = 3
x = np.array([4,2,0,5,7,2,4,9,1,2,3,8,0,2,3])
np.shape(x)
y = x.reshape(L,M, order='F')
print(y)

[[4 2 3]
 [2 4 8]
 [0 9 0]
 [5 1 2]
 [7 2 3]]


In [3]:
# DFT
def DFT(x,N):
    X = np.zeros(N,dtype = 'complex_')
    for k in range(N):
        for n in range(N):
            X[k] = X[k] + x[n]*np.exp(-1j*2*np.pi*k*n/N)
    return X

In [4]:
F = np.zeros((L,M),dtype = 'complex_')
print(np.shape(F))
for l in range(L):
    F[l] = DFT(y[l,:],M) #row
    #np.shape(F)
    print(F[l])

(5, 3)
[9. +0.j        1.5+0.8660254j 1.5-0.8660254j]
[14.+0.j         -4.+3.46410162j -4.-3.46410162j]
[ 9. +0.j         -4.5-7.79422863j -4.5+7.79422863j]
[8. +0.j        3.5+0.8660254j 3.5-0.8660254j]
[12. +0.j         4.5+0.8660254j  4.5-0.8660254j]


In [5]:
G = np.zeros((L,M),dtype = 'complex_')
for l in range(L):
    for q in range(M):
        G[l,q] = F[l,q] * np.exp(-1j*2*np.pi*l*q/N)
print(G)

[[ 9.        +0.j          1.5       +0.8660254j   1.5       -0.8660254j ]
 [14.        +0.j         -2.24520477+4.79156087j -5.25085162+0.65464289j]
 [ 9.        +0.j         -8.80332841-1.87120522j  8.22190912+3.66062979j]
 [ 8.        +0.j          1.90519858-3.06108124j -3.34059644-1.35661911j]
 [12.        +0.j          0.39090314-4.56587283j -4.2216074 +1.78270328j]]


In [6]:
X = np.zeros((L,M),dtype = 'complex_')
for m in range(M):
    X[:,m] = DFT(G[:,m],L) #column
#print(abs(X))
Y = X.reshape(N,)
print(abs(Y))

[52.          8.20656829  4.95715437  4.11892682 21.16279549  8.54400375
  6.7848686  10.82658508 10.82658508  6.7848686   8.54400375 21.16279549
  4.11892682  4.95715437  8.20656829]


In [7]:
print(abs(np.fft.fft(x,N)))

[52.          8.20656829  4.95715437  4.11892682 21.16279549  8.54400375
  6.7848686  10.82658508 10.82658508  6.7848686   8.54400375 21.16279549
  4.11892682  4.95715437  8.20656829]
